version: '2'
services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_USER=canvas
      - POSTGRES_PASSWORD=canvas
      - POSTGRES_DB=canvas
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    # # use https://github.com/tianon/docker-postgres-upgrade for upgrading postgres as needed
    # # also need to add `host all all all md5` to `.data/postgres/pg_hba.conf` after copying over the updated files
    # image: tianon/postgres-upgrade:9.6-to-12
    # environment:
    #   - POSTGRES_USER=canvas
    #   - POSTGRES_PASSWORD=canvas
    #   - POSTGRES_DB=canvas
    # volumes:
    #   - ./.data/postgres:/var/lib/postgresql/data
    #   # copy data from .data/postgres into here before running image
    #   - ./.data/postgres-9.6:/var/lib/postgresql/9.6/data
    #   # copy data from here into .data/postgres after running image
    #   - ./.data/postgres-12:/var/lib/postgresql/12/data
    # ports:
    #   - "15432:5432"
  redis:
    image: redis:6.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./.data/redis:/data
  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8901:8025"
  app: &app
    image: docker-canvas
    build: .
    command: bash -c "./wait-for-it.sh -t 40 db:5432 && /usr/src/entrypoint"
    environment:
      - DB_DRIVER=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=canvas
      - DB_PASSWORD=canvas
      - DB_NAME=canvas
      - RAILS_ENV=production
      - REDIS_SERVER=redis://redis:6379
      - MAIL_SERVER=mail
      - MAIL_PORT=1025
      - MAIL_USERNAME=canvas
      - MAIL_PASSWORD=canvas
      - MAIL_DOMAIN=example.com
      - MAIL_DEFAULT_SENDER_ADDRESS=canvas@example.com
      - MAIL_DEFAULT_SENDER_NAME=Canvas Admin
      - DOMAIN=localhost
      - PASSENGER_STARTUP_TIMEOUT=300
    volumes:
      - ./.data/public/dist/brandable_css:/usr/src/app/public/dist/brandable_css
      - ./deploy/database.yml:/usr/src/app/config/database.yml:ro
      - ./deploy/redis.yml:/usr/src/app/config/redis.yml:ro
      - ./deploy/cache_store.yml:/usr/src/app/config/cache_store.yml:ro
      - ./deploy/outgoing_mail.yml:/usr/src/app/config/outgoing_mail.yml:ro
      - ./deploy/security.yml:/usr/src/app/config/security.yml:ro
      - ./deploy/delayed_jobs.yml:/usr/src/app/config/delayed_jobs.yml:ro
      - ./deploy/domain.yml:/usr/src/app/config/domain.yml:ro
      - ./deploy/consul.yml:/usr/src/app/config/consul.yml:ro
      - ./deploy/dynamic_settings.yml:/usr/src/app/config/dynamic_settings.yml:ro
      - ./deploy/selenium.yml:/usr/src/app/config/selenium.yml:ro
      - ./deploy/vault.yml:/usr/src/app/config/vault.yml:ro
      - ./deploy/development-local.rb:/usr/src/app/config/environments/development-local.rb:ro
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh:ro
      - ./override/oauth2_provider_controller.rb:/usr/src/app/app/controllers/oauth2_provider_controller.rb
      - ./.data/tmp:/usr/src/app/tmp
    ports:
      - "8900:80"
    depends_on:
      - db
      - redis
      - mail
  worker:
    <<: *app
    command: bundle exec script/delayed_job run
    ports:
      - "8902:80"